env:
  - GO111MODULE=on
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

snapshot:
  name_template: "latest"

archives:
  - files:
      - README.md
      - LICENSE
      - config.yaml.example

dockers:
  - image_templates:
      - "gaetancollaud/digitalstrom-mqtt:{{ .Version }}"
      - "gaetancollaud/digitalstrom-mqtt:latest"
    use_buildx: true
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - config.yaml.example
  - image_templates:
      - "gaetancollaud/digitalstrom-mqtt:{{ .Version }}"
      - "gaetancollaud/digitalstrom-mqtt:latest"
    use_buildx: true
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
    extra_files:
      - config.yaml.example
  - image_templates:
      - "gaetancollaud/digitalstrom-mqtt:{{ .Version }}"
      - "gaetancollaud/digitalstrom-mqtt:latest"
    use_buildx: true
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - config.yaml.example

docker_manifests:
  - name_template: gaetancollaud/digitalstrom-mqtt:{{ .Version }}
  - name_template: gaetancollaud/digitalstrom-mqtt:latest
