env:
  - GO111MODULE=on
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - files:
      - README.md
      - LICENSE
      - config.yaml.example

dockers:
  - image_templates:
      - "gaetancollaud/digitalstrom-mqtt:{{ .Version }}"
      - "gaetancollaud/digitalstrom-mqtt:latest"
    use_buildx: true
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - config.yaml.example
    skip_publish: true
  - image_templates:
      - "gaetancollaud/digitalstrom-mqtt:{{ .Version }}-arm"
      - "gaetancollaud/digitalstrom-mqtt:latest-arm"
    use_buildx: true
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
    extra_files:
      - config.yaml.example
    skip_publish: true
  - image_templates:
      - "gaetancollaud/digitalstrom-mqtt:{{ .Version }}-arm64v8"
      - "gaetancollaud/digitalstrom-mqtt:latest-arm64v8"
    use_buildx: true
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - config.yaml.example
    skip_publish: true
docker_manifests:
  - name_template: gaetancollaud/digitalstrom-mqtt:{{ .Version }}
    image_templates:
      - gaetancollaud/digitalstrom-mqtt:{{ .Version }}
      - gaetancollaud/digitalstrom-mqtt:{{ .Version }}-arm
      - gaetancollaud/digitalstrom-mqtt:{{ .Version }}-arm64v8
  - name_template: gaetancollaud/digitalstrom-mqtt:latest
    image_templates:
      - gaetancollaud/digitalstrom-mqtt:latest
      - gaetancollaud/digitalstrom-mqtt:latest-arm
      - gaetancollaud/digitalstrom-mqtt:latest-arm64v8
